# Generated by Django 4.0.4 on 2022-06-07 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['author'], 'verbose_name_plural': 'Books'},
        ),
    ]
