# Generated by Django 4.0.4 on 2022-06-06 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0002_remove_reader_id_reader_reader_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name_plural': 'Books'},
        ),
    ]
